 Network rinha-2024-q1  Creating
 Network rinha-2024-q1  Created
 Container newton-db-1  Creating
 Container newton-db-1  Created
 Container newton-api02-1  Creating
 Container newton-api01-1  Creating
 Container newton-api02-1  Created
 Container newton-api01-1  Created
 Container newton-nginx-1  Creating
 Container newton-nginx-1  Created
Attaching to api01-1, api02-1, db-1, nginx-1
db-1     | The files belonging to this database system will be owned by user "postgres".
db-1     | This user must also own the server process.
db-1     | 
db-1     | The database cluster will be initialized with locale "en_US.utf8".
db-1     | The default database encoding has accordingly been set to "UTF8".
db-1     | The default text search configuration will be set to "english".
db-1     | 
db-1     | Data page checksums are disabled.
db-1     | 
db-1     | fixing permissions on existing directory /var/lib/postgresql/data ... ok
db-1     | creating subdirectories ... ok
db-1     | selecting dynamic shared memory implementation ... posix
db-1     | selecting default max_connections ... 100
db-1     | selecting default shared_buffers ... 128MB
db-1     | selecting default time zone ... UTC
db-1     | creating configuration files ... ok
db-1     | running bootstrap script ... ok
db-1     | sh: locale: not found
db-1     | 2024-02-16 13:02:36.170 UTC [30] WARNING:  no usable system locales were found
db-1     | performing post-bootstrap initialization ... ok
db-1     | syncing data to disk ... ok
db-1     | 
db-1     | 
db-1     | Success. You can now start the database server using:
db-1     | 
db-1     |     pg_ctl -D /var/lib/postgresql/data -l logfile start
db-1     | 
db-1     | initdb: warning: enabling "trust" authentication for local connections
db-1     | You can change this by editing pg_hba.conf or using the option -A, or
db-1     | --auth-local and --auth-host, the next time you run initdb.
db-1     | waiting for server to start....2024-02-16 13:02:37.941 GMT [36] LOG:  starting PostgreSQL 14.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db-1     | 2024-02-16 13:02:37.944 GMT [36] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-16 13:02:37.956 GMT [37] LOG:  database system was shut down at 2024-02-16 13:02:36 GMT
db-1     | 2024-02-16 13:02:37.966 GMT [36] LOG:  database system is ready to accept connections
db-1     |  done
db-1     | server started
db-1     | CREATE DATABASE
db-1     | 
db-1     | 
db-1     | /usr/local/bin/docker-entrypoint.sh: running /docker-entrypoint-initdb.d/init.sql
db-1     | CREATE TABLE
db-1     | CREATE TABLE
db-1     | CREATE INDEX
db-1     | INSERT 0 5
db-1     | 
db-1     | 
db-1     | waiting for server to shut down...2024-02-16 13:02:38.563 GMT [36] LOG:  received fast shutdown request
db-1     | .2024-02-16 13:02:38.565 GMT [36] LOG:  aborting any active transactions
db-1     | 2024-02-16 13:02:38.566 GMT [36] LOG:  background worker "logical replication launcher" (PID 43) exited with exit code 1
db-1     | 2024-02-16 13:02:38.566 GMT [38] LOG:  shutting down
db-1     | 2024-02-16 13:02:38.679 GMT [58] FATAL:  the database system is shutting down
db-1     | 2024-02-16 13:02:38.690 GMT [36] LOG:  database system is shut down
db-1     |  done
db-1     | server stopped
db-1     | 
db-1     | PostgreSQL init process complete; ready for start up.
db-1     | 
db-1     | 2024-02-16 13:02:38.780 GMT [1] LOG:  starting PostgreSQL 14.1 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20211027) 10.3.1 20211027, 64-bit
db-1     | 2024-02-16 13:02:38.780 GMT [1] LOG:  listening on IPv4 address "0.0.0.0", port 5432
db-1     | 2024-02-16 13:02:38.780 GMT [1] LOG:  listening on IPv6 address "::", port 5432
db-1     | 2024-02-16 13:02:38.787 GMT [1] LOG:  listening on Unix socket "/var/run/postgresql/.s.PGSQL.5432"
db-1     | 2024-02-16 13:02:38.797 GMT [59] LOG:  database system was shut down at 2024-02-16 13:02:38 GMT
db-1     | 2024-02-16 13:02:38.804 GMT [1] LOG:  database system is ready to accept connections
nginx-1  | /docker-entrypoint.sh: /docker-entrypoint.d/ is not empty, will attempt to perform configuration
nginx-1  | /docker-entrypoint.sh: Looking for shell scripts in /docker-entrypoint.d/
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/10-listen-on-ipv6-by-default.sh
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Getting the checksum of /etc/nginx/conf.d/default.conf
nginx-1  | 10-listen-on-ipv6-by-default.sh: info: Enabled listen on IPv6 in /etc/nginx/conf.d/default.conf
nginx-1  | /docker-entrypoint.sh: Sourcing /docker-entrypoint.d/15-local-resolvers.envsh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/20-envsubst-on-templates.sh
nginx-1  | /docker-entrypoint.sh: Launching /docker-entrypoint.d/30-tune-worker-processes.sh
nginx-1  | /docker-entrypoint.sh: Configuration complete; ready for start up
nginx-1  | 2024/02/16 13:02:43 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.4:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:02:43 [error] 28#28: *1 connect() failed (111: Connection refused) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:02:45 [error] 28#28: *4 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:02:47 [error] 28#28: *5 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
api02-1 exited with code 137
api01-1 exited with code 137
nginx-1  | 2024/02/16 13:02:49 [error] 28#28: *6 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:02:51 [error] 28#28: *7 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:02:53 [error] 28#28: *8 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:03:55 [error] 28#28: *9 upstream timed out (110: Connection timed out) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:13 [error] 28#28: *9 connect() failed (113: No route to host) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.4:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:19 [error] 28#28: *12 connect() failed (113: No route to host) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:19 [error] 28#28: *12 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:21 [error] 28#28: *14 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:23 [error] 28#28: *15 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:28 [error] 28#28: *16 connect() failed (113: No route to host) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.4:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:28 [error] 28#28: *16 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:33 [error] 28#28: *18 connect() failed (113: No route to host) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:33 [error] 28#28: *18 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:35 [error] 28#28: *20 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:37 [error] 28#28: *21 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:42 [error] 28#28: *22 connect() failed (113: No route to host) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.4:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:42 [error] 28#28: *22 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:47 [error] 28#28: *24 connect() failed (113: No route to host) while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://172.22.0.3:4000/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:47 [error] 28#28: *24 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:49 [error] 28#28: *26 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1  | 2024/02/16 13:04:51 [error] 28#28: *27 no live upstreams while connecting to upstream, client: 172.22.0.1, server: , request: "GET /clientes/1/extrato HTTP/1.1", upstream: "http://api/clientes/1/extrato", host: "localhost:9999"
nginx-1 exited with code 0
nginx-1 exited with code 0
db-1     | 2024-02-16 13:04:54.115 GMT [1] LOG:  received fast shutdown request
db-1     | 2024-02-16 13:04:54.118 GMT [1] LOG:  aborting any active transactions
db-1     | 2024-02-16 13:04:54.119 GMT [1] LOG:  background worker "logical replication launcher" (PID 65) exited with exit code 1
db-1     | 2024-02-16 13:04:54.119 GMT [60] LOG:  shutting down
db-1     | 2024-02-16 13:04:54.163 GMT [1] LOG:  database system is shut down
db-1 exited with code 0
